Enable rel with deb info build type
nextcloud/client-building pull request #129
Opened 2024-12-04 09:56 UTC by mgallien

2024-12-04 10:32 UTC, mgallien commented
enable https://github.com/nextcloud-gmbh/brander/pull/896

2025-06-30 13:32 UTC, nilsding requested changes

2025-07-01 08:43 UTC, nilsding approved these changes

2025-08-04 09:59 UTC, merged

2025-12-19 17:01 UTC, mgallien commented
/backport to stable-4.0